### ISSUE TITLE
Does this run on JRUBY?

### ISSUE THREAD

**Issue by henry74** [rdvdijk/lame#1]
Getting the following error on Ubuntu 13.04.  I have all the lame libraries installed:

```
LoadError: Could not open library 'libmp3lame' : libmp3lame: cannot open shared object file: No such file or directory. Could not open library 'libmp3lame.so' : libmp3lame.so: cannot open shared object file: No such file or directory
from /home/user/.rbenv/versions/jruby-1.7.4/lib/ruby/shared/ffi/library.rb:95:in `ffi_lib'
```

I'm running JRuby 1.7.4

Seems like this is using the ruby to java bridge gem - would be interested in understanding how and why it's using it to speak to the lame library if it's also using the ffi to interface with the C extension

**Comment by rdvdijk** [comment]
I've released a new version today and have added this to the README.
